theme = "solarized-dark"
icons = "awesome"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = false
# interval = 2

[[block]]
block = "pacman"
interval = 1200

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# 

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

# [[block]]
# block = "custom"
# cycle = ["echo ON", "echo OFF"]
# on_click = "<command>"
# interval = 1
 

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp3s0"
#ssid = true
#ip = true
speed_up = false
graph_up = false
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "temperature"
collapsed = true
interval = 10


[[block]]
block = "battery"
interval = 10
device = "BAT1"
# show = "both"

[[block]]
block = "custom"
#cycle = ["echo ON", "echo OFF"]
command = "echo LOCK"
on_click = "xdotool key super+q"
interval = 1000
